### ISSUE TITLE
Standard Working Hours

### ISSUE THREAD

**Issue by BrianBerzins** [target/pod-reaper#18]
There has been a request for a rule that could be used to control when pods are reaped relative to the time of the day/week.

Use case: I only want to clean stuff up after standard working hours.
Use case: I want to periodically kill pods, but only when most people are in the office.

**Comment by BrianBerzins** [comment]
First pass at this was done yesterday, but I didn't like the complexity of the implementation and it started to make me think that I was missing a much simpler solution. 

At the end of it all, I had three major thoughts.

1. poll interval could be replaced with cron on the reap cycle
1. this feature could be done just using the cron job above
1. run duration is actually completely unsafe... and I don't know how I missed that... because if it is killed the run duration is refreshed.

**Comment by BrianBerzins** [comment]
Have a local working version that uses: 
https://godoc.org/github.com/robfig/cron

unfortunately, this would be breaking backwards compatibility because it removes the `POLL_INTERVAL` environment variable in favor of a `SCHEDULE` environment variable. On the plus side, it gives MUCH better control over when pods are inspected for reaping.

**Comment by JordanSussman** [comment]
@BrianBerzins I think this change is worthwhile enough to represent a breaking change. Would you still like to have #20 merged and released or implement this change instead?

**Comment by BrianBerzins** [comment]
@JordanSussman I actually have a local build with cron fully implemented and testing. I can incorporate the `RUN_DURATION` logging incorporated into that. 

Those local changes take advantage of some of the testing cleanup I did in #19 though, so that would still have to go first.

**Comment by JordanSussman** [comment]
Alright, I'll review #19 @BrianBerzins.

**Comment by BrianBerzins** [comment]
this was completed as part of #21
