### ISSUE TITLE
cannot use comma separated values in environment variables via `kubectl run`

### ISSUE THREAD

**Issue by brianberzins** [target/pod-reaper#22]
`kubectl run` cannot be used when an environment variables has commas due to the way that the command parses the command line flags. More investigation needs to happen about this, as it might have been fixed upstream.

**Comment by BrianBerzins** [comment]
workaround: don't use `kubectl run` and instead use a pod-spec and apply with `kubectl apply -f pod-spec.yml`. An example is included in the repo. 

Leaving this issue open as it's still just a workaround. It'd be nice to have a simple command that can be used to create and run a one-time reaper.

**Comment by brianberzins** [comment]
Particularly with the use of service accounts, I think this is best left to deploying manifest files over single line runs. Closing for now, but would be happy to revisit if there's a desire!
