### ISSUE TITLE
Configure logging via environment variable.

### ISSUE THREAD

**Issue by brianberzins** [target/pod-reaper#33]
Logging level should be configurable from environment variables. It's possible that this is already done by the logrus library, in which case the only changes would need to be documentation

**Comment by JordanSussman** [comment]
According to the logrus documentation: `Logrus has no notion of environment.`. However, they do list the workaround of: 

```go
import (
  log "github.com/sirupsen/logrus"
)

init() {
  // do something here to set environment depending on an environment variable
  // or command-line flag
  if Environment == "production" {
    log.SetFormatter(&log.JSONFormatter{})
  } else {
    // The TextFormatter is default, you don't actually have to do this.
    log.SetFormatter(&log.TextFormatter{})
  }
}
```

Should be easy enough to do something like:

```go
package main

import (
	"github.com/sirupsen/logrus"
)

func main() {
	logrus.SetFormatter(&logrus.JSONFormatter{})
	reaper := newReaper()
	reaper.harvest()
	logrus.Info("pod reaper is exiting")
	level := os.Getenv("REAPER_DEBUG")
	if level == true {
		log.SetLevel(log.DebugLevel)
	}
}

```

**Comment by b1tkeeper** [comment]
> According to the logrus documentation: `Logrus has no notion of environment.`. However, they do list the workaround of:
> 
> ```go
> import (
>   log "github.com/sirupsen/logrus"
> )
> 
> init() {
>   // do something here to set environment depending on an environment variable
>   // or command-line flag
>   if Environment == "production" {
>     log.SetFormatter(&log.JSONFormatter{})
>   } else {
>     // The TextFormatter is default, you don't actually have to do this.
>     log.SetFormatter(&log.TextFormatter{})
>   }
> }
> ```
> 
> Should be easy enough to do something like:
> 
> ```go
> package main
> 
> import (
> 	"github.com/sirupsen/logrus"
> )
> 
> func main() {
> 	logrus.SetFormatter(&logrus.JSONFormatter{})
> 	reaper := newReaper()
> 	reaper.harvest()
> 	logrus.Info("pod reaper is exiting")
> 	level := os.Getenv("REAPER_DEBUG")
> 	if level == true {
> 		log.SetLevel(log.DebugLevel)
> 	}
> }
> ```

Not supporting envrionment variables is a bad decision for logging library :)
