### ISSUE TITLE
Option to prevent pod-reaper from killing all pods in a replica set at the same time

### ISSUE THREAD

**Issue by brianberzins** [target/pod-reaper#36]
This is one that I have discussed with a few people in person. On one hand: it would allow for a safer learning curve: particularly for things that are clustered.

A couple of options:
1. optional variable to prevent more than `n` pods for any one replica set from being deleted at one time.
1. optional variable to ensure that pod reaper does not kill pods to reduce a replica set below `n` pods.

There is some fair discussion about whether or not this is a feature pod-reaper should have. I would like to avoid letting people hide problems with this option. For example: if you're running a single pod, and we're using option 2: then pod reaper would effectively be whitelisting that pod. Another example, in the first case: a small `n` value doesn't necessarily provide much value to large replica sets.

**Comment by beaucfr** [comment]
What would be the suggestion for an HA type deployment to maintain uptime?

**Comment by brianberzins** [comment]
> What would be the suggestion for an HA type deployment to maintain uptime?

If you're using the random number rule to invoke chaos, there's currently nothing stopping it from taking out all pods in a specific replica set. If you are running in two different clusters and balancing between them (like east/central), running pod reaper on only one would ensure that you aren't left without service. On the other hand: if you wan run pod reaper with that chaos chance and NOT experience downtime, then you know you're availability is pretty dang good.  

The likelihood of the reaper killing all pods on a given reaping cycle is `c^n` where c is the chaos chance (between 0 and 1) and n is the number of replicas. You could use this to calculate out your error budget/risk tolerance.

**Comment by brianberzins** [comment]
I think I'm going to close this one for now, but I'd be willing to look into this more if people are interested.
