### ISSUE TITLE
Log messages not parsed by Stackdriver

### ISSUE THREAD

**Issue by MrWako** [target/pod-reaper#47]
Firstly thank you for creating this tool - I really like its simplicity. I've been experimenting with it on GCP and whilst not really an issue with pod-reaper, the default Logrus structured logs do not get handled well by the fleuntd/stackdriver collectors, and all the log messages, regardless of severity, get logged as Errors.

I've put together a small PR to allow for different formatting of the logs, let me know what you think.

**Comment by brianberzins** [comment]
Oh wow! I remember looking at this! I think it's actually deeper than logrus! I think I recall it actually being a golang thing (that some logging frameworks built around!)

Greatly appreciate the kind words. I'll see what I can do to help make it work :-)

**Comment by brianberzins** [comment]
I wish I could find where I found this when I first looked into everything-getting-logged-to-`stderr`... but I haven't been able to find it yet.

Some interesting back and forth here:
https://github.com/sirupsen/logrus/issues/403#issuecomment-332970055

**Comment by brianberzins** [comment]
@MrWako 
Merged and released as 2.5.0! Can you confirm that it's working for you with stack driver?

If everything logging to stderr is painful, I can dig deeper into this. In the most extreme case, it should be possible to force it into using stdout (but I'd want to really understand why they chose stderr if I'm looking to change it)

**Comment by brianberzins** [comment]
Marking as closed, if something isn't working, please feel free to reopen!
