### ISSUE TITLE
Dry run mode

### ISSUE THREAD

**Issue by therc** [target/pod-reaper#55]
I've started looking at pod-reaper after reaping 10,000 old pods in my cluster (don't ask...). This is probably the first of several feature requests, sorry if they're a bit spammy.

One feature that would make adoption easier and less risky is a dry run mode, where it does all the work, but doesn't kill anything — and probably exits right away.

**Comment by brianberzins** [comment]
Totally doable. I think a few people have asked for this, so now's probably as good of time as any.

**Comment by therc** [comment]
That was quick, thanks a lot! May you be forever gifted with good health and an exquisite taste in ties...
I'll start using it and, unless it blows up the cluster somehow in dry run mode, I'll file the other feature requests and probably some PRs. Thanks again.
