### ISSUE TITLE
Update Dependencies to use Go Modules

### ISSUE THREAD

**Issue by GregoryDosh** [target/pod-reaper#57]
We should consider updating the dependencies to use the newer built in modules of go.

https://blog.golang.org/migrating-to-go-modules

**Comment by brianberzins** [comment]
I've also been meaning to switch off glide for awhile... so maybe this is a two bird situation!

**Comment by ojagodzinski** [comment]
> We should consider updating the dependencies to use the newer built in modules of go.

https://github.com/target/pod-reaper/pull/58

**Comment by brianberzins** [comment]
closing this because it should be resolved with #58
