### ISSUE TITLE
Docker builds no longer happening automatically

### ISSUE THREAD

**Issue by brianberzins** [target/pod-reaper#72]
@slushpupie 
With recent changes to docker's licensing, the automated builds are now a payed feature.
It doesn't look like I have permissions to upload new builds myself, and I was previously relying on the automated builds.

Do you have thoughts on this?
I'm pretty upset with Docker's license changes overall, but I'll have to find time to pickup podman or an alternative. 
Is there a reasonable thing to do in the meantime?

**Comment by slushpupie** [comment]
We (Target) are working on what to do at this point.  I'll get back to you on this once we have that figured out (hopefully in short order)

**Comment by brianberzins** [comment]
Not perfectly clear on this, but given this is open sourced, I might be able to setup github actions.
Would need someone on the Target side to inject a working token to do the docker push.

**Comment by brianberzins** [comment]
@slushpupie got a chance to play around with github actions tonight, and have a build working over on a fork. Having done some work with ci tools in the past, I have a paranoid nagging about the security of secrets happening that I want to make sure is actually close. If it is, I think it's a solid option. Otherwise, I'll post an update here.

More to come.

**Comment by slushpupie** [comment]
Sorry, I've been meaning to get back to you on this.  I am working out how to get our service accounts on our Docker Hub account, and once we get that complete, we will have a secret stored at github.com/target for publishing docker images.

**Comment by brianberzins** [comment]
Awesome! Thanks!
