### ISSUE TITLE
Publish to docker hub

### ISSUE THREAD

**Issue by JordanSussman** [target/pod-reaper#8]
Need to get access from @jmccann to publish to https://hub.docker.com/r/target/.

**Comment by JordanSussman** [comment]
Manually published to https://hub.docker.com/r/target/pod-reaper/, but would like to look into automated publishing with either docker store integration or travis CI. Any preference @BrianBerzins? 

Will also be nice once [multi-stage builds](https://ordina-jworks.github.io/conference/2017/04/18/DockerCon-Multi-Stage-Builds-And-More.html) are in the stable version version of docker.

**Comment by BrianBerzins** [comment]
I'm​a fan on "whatever Target has done with open source" thus far! I'll make a note to talk with Jake about it unless we have some standard!

**Comment by BrianBerzins** [comment]
I now have write access to the docker repo for this, so I should be able to get this rolling sometime this week.

**Comment by BrianBerzins** [comment]
haven't forgotten about this! but with multistage docker builds this gets MUCH easier... 
working on it now while also vetting out multistage docker builds!

**Comment by BrianBerzins** [comment]
This is fully proven out on the beta version of docker... which is currently on track for non-beta release on docker hub sometime in june!

**Comment by BrianBerzins** [comment]
*cough* still waiting...
https://github.com/docker/hub-feedback/issues/1039

**Comment by JordanSussman** [comment]
Looks like Docker officially rolled out the new Docker EE version to Dockerhub. @BrianBerzins do you have access to create automated builds in the github org? If you don't have access I can both Jake to do it tomorrow.

**Comment by BrianBerzins** [comment]
Going to test this out shortly

**Comment by BrianBerzins** [comment]
https://hub.docker.com/r/target/pod-reaper/tags/
