### ISSUE TITLE
Pod reaping strategy

### ISSUE THREAD

**Issue by tomzx** [target/pod-reaper#82]
Hello!

Thank you for pod-reaper!

One feature we would find useful is to have the ability to decide which pods should be reaped when `max_pods` is defined. A few strategies that come to mind:
* Random: any pod that matches the defined rules gets terminated.
* Age based: sort matching pods by age and terminate the youngest/oldest.
* Annotation based: Based on the [pod-deletion-cost](https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/#pod-deletion-cost) annotation, or any other annotation that could be configured. In this case an integer value would be set on the pods and we would sort based on the same principles used for `pod-deletion-cost`.

The current behavior is `random` based on observations.

**Comment by brianberzins** [comment]
Just back from vacation, I think this is a solid idea. 
I think the current behavior relies on whatever order the API server default ordering is (I *thought* it wasn't random, but I also don't think it make any intuitive sense when I looked it up).

Feels like a pretty easy add. I'll try to through up a PR with at least one of them soon!

**Comment by GregoryDosh** [comment]
This should hopefully be addressed in #85 so give it a spin and let @brianberzins or I know if you have other questions or ideas. He did the bulk of the implementation with me pairing along the way and learning.

**Comment by brianberzins** [comment]
@tomzx Released as 2.12.0 (and latest).
Would love to hear if this works for you: good, bad, or other!

**Comment by tomzx** [comment]
@brianberzins We'll give it a try next week. Thanks for the new feature!

**Comment by tomzx** [comment]
We've been using the `POD_SORTING_STRATEGY=oldest-first` variant in production for a while now, works well. Thanks again! :+1:
